CREATE TABLE [dbo].[FriendRequests](
	[UserId] [int] NOT NULL,
	[RequestedUserId] [int] NOT NULL,
	[Timestamp] [date] NOT NULL,
 CONSTRAINT [PK_FriendRequests] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RequestedUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


